    <html>
    <head>
        <title>@yield('title')</title>
        @extends('base.style')
        @yield('moreStyles')
    </head>
    <body>
        <div>
            @yield('content')
        </div>
        @extends('base.script')
        @yield('moreScripts')
    </body>
</html>
